#' Proportion of Matched DEGs
#'
#' @param sim_data The simulated dataset to be evaluated.
#' @param group Group(or cluster) assignment of every cells in columns of matrix.
#' @param group_combn The combinations of two groups generated by [utils::combn()] function.
#' @param sim_DEGs A list with `xxxvsxxx` format of names containing the DEGs of different paired groups.
#' @importFrom purrr map
#' @importFrom BiocGenerics Reduce intersect
#' @export
true_DEGs_proportion <- function(
  sim_data,
  group,
  group_combn,
  sim_DEGs
){
  ## DGA method
  DGA_method <- c("edgeRQLF",
                  "edgeRQLFDetRate",
                  "MASTcpmDetRate",
                  "MASTcpm",
                  "limmatrend",
                  "limmavoom")
  true_prop <- list()
  DEGs_num <- c()
  for(i in 1:ncol(group_combn)){
    group_compare <- group_combn[, 1]
    compare_name <- paste0(group_compare, collapse = "vs")
    sub_data <- sim_data[, which(group %in% group_compare)]
    sub_group <- group[which(group %in% group_compare)]
    sub_DEGs <- sim_DEGs[[compare_name]]
    all_method_DEGs <- purrr::map(DGA_method, function(method){
      DEA_result <- simutils::perform_DEA(data = sim_data,
                                          group = sub_group,
                                          method = method)
      rownames(DEA_result)[DEA_result$"PValue" < 0.05]
    })
    intersect_genes_methods <- BiocGenerics::Reduce(x = all_method_DEGs, f = intersect)
    intertect_genes <- BiocGenerics::intersect(intersect_genes_methods, sub_DEGs)
    prop <- length(intertect_genes)/length(sub_DEGs)
    DEGs_num <- append(DEGs_num, length(sub_DEGs))
    true_prop[compare_name] <- prop
  }
  weighted_true_prop <- sum(unname(unlist(true_prop)) * (DEGs_num / sum(DEGs_num)))
  return_list <- dplyr::lst(true_prop,
                            DEGs_num,
                            weighted_true_prop)
  return(return_list)
}

