#' Check Class of Parameter Objects
#'
#' Make sure all the parameters are generated by \code{param_numeric},
#' \code{param_character}, \code{param_Boolean} or \code{param_integer} function.
#'
#' @param parameters_list A list consists of defined parameter.
#' @seealso [param_numeric()], [param_character()], [param_Boolean()], [param_integer()]
#' @importFrom assertthat assert_that
#' @export
#'
is_define_parameters <- function(parameters_list){
  purrr::map(parameters_list, .f = function(x){
    assertthat::assert_that(is.list(x))
    if(!any(base::grepl(x = unlist(class(x)), pattern = "_parameter"))){
      cat(x[["id"]], "is not supported", sep = " ")
      return(FALSE)
    }else return(TRUE)
  })

}


#' Generate Parameter sets
#'
#' @description Collect and return all defined parameters.
#'
#' @param ... Defined lists of parameters.
#' @seealso [param_numeric()], [param_character()], [param_Boolean()], [param_integer()]
#' @importFrom purrr map
#' @importFrom stats setNames
#' @return A list contains the parameters of estimating process and simulation process
#' @export
#' @examples
#' param_set <- parameter_sets(
#' param_character(id = 'dimension_method',
#'                 default = "UMAP",
#'                 alternatives = c("UMAP", "TSNE", "PCA"),
#'                 description = "The algorithm to use for dimensionality reduction."),
#' param_Boolean(id = "verbose",
#'               default = TRUE,
#'               process = 'estimation',
#'               description = "Whether to return the information during the process"),
#' param_integer(id = "group_num",
#'               default = 1L,
#'               lower = 1L,
#'               upper = 50L,
#'               border = TRUE,
#'               description = "How many groups to be simulated"),
#' param_numeric(id = "probability",
#'               default = 0.5,
#'               lower = 0,
#'               upper = 1,
#'               border = TRUE,
#'               process = 'estimation',
#'               description = "The probability to select the right number")
#' )
parameter_sets <- function(...){

  # Extract parameter names and set list names
  parameters_name <- unlist(purrr::map(list(...), function(x) x[["id"]]))
  parameters_list <- list(...) %>% setNames(parameters_name)

  # Check class of parameter object
  is_define_parameters(parameters_list)

  # Define the parameters of two processes
  estimate_process <- parameters_list[unlist(purrr::map(parameters_list, .f = function(x) x[["process"]] == "estimation"))]
  simulation_process <- parameters_list[unlist(purrr::map(parameters_list, .f = function(x) x[["process"]] == "simulation"))]

  # Return a list
  list(estimate_process = estimate_process,
       simulation_process = simulation_process)

}


#' Define Numeric Parameters
#'
#' @description  Define a numeric parameter.
#'
#' @param id A parameter name.
#' @param type The type of parameter. Must be a numeric.
#' @param default The default value.
#' @param lower The lowest range of this parameter.
#' @param upper The highest range of this parameter.
#' @param border Boolean. Whether the default value can get to the range border.
#' @param description The description information of this parameter.
#' @param process Two options, simulation or estimation. Which process does this
#' parameter involved in.
#'
#' @return A list.
#' @export
#'
#' @examples
#' probability <- param_numeric(
#' id = "probability",
#' default = 0.5,
#' lower = 0,
#' upper = 1,
#' border = TRUE,
#' description = "The probability to select the right number"
#' )
param_numeric <- function(id,
                          type = "numeric",
                          default,
                          lower = NULL,
                          upper = NULL,
                          border = TRUE,
                          description = NULL,
                          process = "simulation"){
  assertthat::assert_that(is.character(id),
                          is.numeric(default))
  if(type != "numeric"){
    stop("This is not fit for other types except for numeric values")
  }

  if(is.null(lower)){
    cat(id, ": ", "The parameter lower is not defined and will be set to -Inf\n")
    lower <- -Inf
  }
  if(is.null(upper)){
    cat(id, ": ", "The parameter upper is not defined and will be set to Inf\n")
    upper <- Inf
  }
  if(!is.infinite(lower) & !is.infinite(upper)){
    if(lower >= upper){
      stop('Lower value must be smaller than upper value')
    }
    if(!border){
      if(default == lower | default == upper){
        stop("The defaul value can not euqal to the lower or the upper\nPlease reset!")
      }
    }
  }
  tibble::lst(id,
              type,
              default,
              lower,
              upper,
              border,
              process,
              description) %>% add_class("numeric_parameter")
}


#' Define Integer Parameters
#'
#' @description Define an integer parameter.
#'
#' @param id A parameter name.
#' @param type The type of parameter. Must be an integer.
#' @param default The default value.
#' @param lower The lowest range of this parameter.
#' @param upper The highest range of this parameter.
#' @param border Boolean. Whether the default value can get to the range border.
#' @param description The description information of this parameter.
#' @param process Two options, simulation or estimation. Which process does this
#' parameter involved in.
#'
#' @return A list.
#' @export
#'
#' @examples
#' group_num <- param_integer(
#' id = "group_num",
#' default = 1L,
#' lower = 1L,
#' upper = 50L,
#' border = TRUE,
#' process = "estimation",
#' description = "How many groups to be simulated"
#' )
param_integer <- function(id,
                          type = "integer",
                          default,
                          lower = NULL,
                          upper = NULL,
                          border = TRUE,
                          description = NULL,
                          process = "simulation"){

  assertthat::assert_that(is.character(id),
                          is.integer(default))
  if(type != "integer"){
    stop("This is not fit for other types except for integers")
  }

  if(!is.null(lower) & !is.null(upper)){
    if(lower >= upper){
      stop('Lower value must be smaller than upper value')
    }
  }
  if(!border){
    if(default == lower | default == upper){
      stop("The defaul value can not euqal to the lower or the upper\nPlease reset!")
    }
  }
  tibble::lst(id,
              type,
              default,
              lower,
              upper,
              border,
              process,
              description) %>% add_class("integer_parameter")

}


#' Define Logical Parameters
#'
#' @description Define a Boolean parameter.
#'
#' @param id A parameter name.
#' @param type The type of parameter. Must be a logical value.
#' @param default The default value. TRUE or FALSE.
#' @param description The description information of this parameter.
#' @param process Two options, simulation or estimation. Which process does this
#' parameter involved in.
#'
#' @return A list.
#' @export
#'
#' @examples
#' verbose <- param_Boolean(
#' id = "verbose",
#' default = TRUE,
#' description = "Whether to return the information during the process"
#' )
param_Boolean <- function(id,
                          type = "logical",
                          default,
                          description = NULL,
                          process = "simulation"){
  assertthat::assert_that(is.character(id),
                          is.logical(default))
  if(type != "logical"){
    stop("This is not fit for other types except for logical values")
  }
  tibble::lst(id,
              type,
              default,
              process,
              description) %>% add_class("Boolean_parameter")

}


#' Define Character Parameters
#'
#' @description  Define a character parameter.
#'
#' @param id A parameter name.
#' @param type The type of parameter. Must be characters.
#' @param default The default values. Length to one or more.
#' @param alternatives Options that can be chosen.
#' @param description The description information of this parameter.
#' @param process Two options, simulation or estimation. Which process does this
#' parameter involved in.
#'
#' @return A list.
#' @export
#'
#' @examples
#' dimension_method <- param_character(
#' id = 'dimension_method',
#' default = "UMAP",
#' process = "estimation",
#' alternatives = c("UMAP", "TSNE", "PCA"),
#' description = "The algorithm to use for dimension reduction."
#' )
param_character <- function(id,
                            type = "character",
                            default,
                            alternatives,
                            description = NULL,
                            process = "simulation"){

  assertthat::assert_that(is.character(id),
                          is.character(default))
  if(type != "character"){
    stop("This is not fit for other types except for characters")
  }

  if(!default %in% alternatives){
    stop("The default value is not in your alternatives. Please check the spelling and input")
  }

  tibble::lst(id,
              type,
              default,
              alternatives,
              process,
              description) %>% add_class("character_parameter")
}


#' Define Vector Parameters
#'
#' @param id A parameter name.
#' @param type The type of parameter.
#' @param default The default values. Length to one or more.
#' @param description The description information of this parameter.
#' @param process Two options, simulation or estimation. Which process does this
#' parameter involved in.
#'
#' @return A list.
#' @export
#'
#' @examples
#' path_method <- param_vector(
#' id = 'path',
#' default = c(0,1,2,3),
#' process = "simulation"
#' )
param_vector <- function(id,
                         type = "vector",
                         default,
                         description = NULL,
                         process = "simulation"){
  assertthat::assert_that(is.character(id))
  tibble::lst(id,
              type,
              default,
              process,
              description) %>% add_class("vector_parameter")

}


#' Define Inference Dataset Parameter
#'
#' @param id A parameter name. Default is NULL, which means no reference matrix input.
#' @param type The type of parameter. Default is NULL. See \code{alternatives}.
#' @param alternatives Alternative options.
#' @param description The description information of this parameter.
#' @param process Two options, simulation or estimation. Which process does this
#' parameter involved in.
#'
#' @return A list.
#' @export
#'
#' @examples
#' matrix_input_method <- param_inference(
#' id = 'matrix_input',
#' type = "SingleCellExperiment",
#' process = "estimation",
#' description = "The matrix to use for parameters estimating."
#' )
param_inference <- function(id = NULL,
                            type = NULL,
                            alternatives = c("matrix", "SingleCellExperiment"),
                            description = NULL,
                            process = "simulation"){
  assertthat::assert_that(is.character(id))
  assertthat::assert_that(type %in% alternatives)
  tibble::lst(id,
              type,
              alternatives,
              process,
              description) %>% add_class("inference_parameter")
}


#' Define Dataframe Object Parameter
#'
#' @param id A parameter name. Default is NULL, which means no dataframe object input.
#' @param type The type of parameter. Must be a data.frame or tibble.
#' @param description The description information of this parameter.
#' @param process Two options, simulation or estimation. Which process does this
#' parameter involved in.
#'
#' @return A list.
#' @export
#'
#' @examples
#' network_input <- param_dataframe(
#' id = 'network',
#' process = "simulation",
#' description = "The network information is used to show the relationship of nodes."
#' )
param_dataframe <- function(id = NULL,
                            type = c("data.frame", "tibble"),
                            description = NULL,
                            process = "simulation"){
  assertthat::assert_that(is.character(id))
  tibble::lst(id,
              type,
              process,
              description) %>% add_class("dataframe_parameter")
}
