#' Set Parameter Values
#'
#' @param method The methods where you want to change the parameters from. One or more methods are supported.
#' @param param_list A list generated by [simmethods::get_method()].
#' @param reset e.g. c("nCells:2000", "nGenes:20000", "nBatches:10") or a list for setting parameters in more methods. See examples.
#' @seealso [simmethods::get_method()]
#' @return An update list of parameters
#' @importFrom purrr map
#' @importFrom stringr str_split
#' @export
#'
set_param <- function(method, param_list, reset){

  purrr::map(method, .f = function(method){
    # Make sure the method name is right
    if(!method %in% names(reset)) stop(base::paste(method, " does not match the method name in reset"))
    # Extract the new parameters
    param_reset <- reset[[method]]
    # Get parameter names of the method
    get_param_name <- .get_param_name(method = method, param_list = param_list)
    for(i in param_reset){
      # Make sure the parameter name is right
      param_value <- as.character(stringr::str_split(i, pattern = ":", simplify = T))
      param <- param_value[1]
      if(!param %in% get_param_name[[method]]){
        stop(base::paste(param, ' does not match the parameter name in param_list'))
      }else{
        # Replacement
        value <- param_value[2]
        param_list[[method]][[base::paste0(method, "_parameters")]][["parameters"]][[param]][["default"]] <- value
      }
    }
  })

}



.get_param_name <- function(method, param_list){
  param_name <- purrr::map(method, .f = function(method){
    names(param_list[[method]][[base::paste0(method, "_parameters")]][["parameters"]])
  }) %>% setNames(method)
  param_name
}
