#' Set Parameter Values
#'
#' @param method The methods where you want to change the parameters from. One or more methods are supported.
#' @param param_list A list generated by [simmethods::get_method()].
#' @param reset e.g. c("nCells:2000", "nGenes:20000", "nBatches:10") or a list for setting parameters in more methods. See examples.
#' @seealso [simmethods::get_method()]
#' @return An update list of parameters
#' @importFrom purrr map
#' @importFrom stringr str_split
#' @export
#' @examples
#' # method <- c("splat", "PROSSTT")
#' # reset <- list(splat = c("nCells:2000", "nGenes:20000"),
#' #               PROSSTT = c("nCells:5000", "nGenes:5000"))
#' # devtools::install_github("duohongrui/simmethods")
#' # param_list <- simmethods::get_method()
#' # new_param_list <- set_param(method = method, param_list = param_list, reset = reset)
set_param <- function(method, param_list, reset){

  for(method in method){
    # Make sure the method name is right
    if(!method %in% names(reset)) stop(base::paste(method, " does not match the method name in reset"))
    # Extract the new parameters
    param_reset <- reset[[method]]
    # Get parameter names of the method
    get_param_name <- .get_param_name(method = method, param_list = param_list)
    for(i in param_reset){
      # Make sure the parameter name is right
      param_value <- as.character(stringr::str_split(i, pattern = ":", simplify = T))
      param <- param_value[1]
      if(!param %in% get_param_name[[method]]){
        stop(base::paste(param, ' does not match the parameter name in param_list'))
      }else{
        # Replacement
        value <- param_value[2]
        class_name <- param_list[[method]][[base::paste0(method, "_parameters")]][[param]][["type"]]
        if(class_name == "integer"){
          value <- as.integer(value)
        }else if(class_name == "numeric"){
          value <- as.numeric(value)
        }else if(class_name == "logic"){
          value <- as.logical(value)
        }else if(class_name == "character"){
          value <- as.character(value)
        }else if(class_name == "vector"){
          value <- as.vector(value)
        }
        param_list[[method]][[base::paste0(method, "_parameters")]][[param]][["default"]] <- value
      }
    }
  }

}



.get_param_name <- function(method, param_list){
  param_name <- purrr::map(method, .f = function(method){
    names(param_list[[method]][[base::paste0(method, "_parameters")]][["parameters"]])
  }) %>% setNames(method)
  param_name
}
